# Generated by Django 4.2 on 2024-04-02 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='card',
            name='check_status',
            field=models.BooleanField(choices=[(False, 'Не проверено'), (True, 'Проверено')], db_column='CheckStatus', default=0),
        ),
        migrations.AlterField(
            model_name='card',
            name='category_id',
            field=models.ForeignKey(db_column='CategoryID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cards.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='card',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, db_column='UploadDate', verbose_name='Дата загрузки'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_column='Name', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(db_column='Name', max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='cardtags',
            unique_together={('card', 'tag')},
        ),
    ]
